  
steps:
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'JarCreation/Word-count-beam'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']
    
  - id: "jar creation"
    name: maven:3.6.3-jdk-11
    dir: 'Word-count-beam'
    entrypoint: mvn
    args: ['clean','package']
    waitFor: ['get build number']
    
  - id: "jar location"
    name: gcr.io/cloud-builders/gsutil
    args: ['cp','/workspace/Word-count-beam/target/word-count-beam-bundled-0.0.1-SNAPSHOT.jar','gs://geometric-edge-296513/jars']
    waitFor: ['jar creation']
